[package]
name = "clap-validator"
version = "0.3.2"
edition = "2024"
license = "MIT"
rust-version = "1.87.0"  # MSRV

description = "A validator and automatic test suite for CLAP plugins"
readme = "README.md"
repository = "https://github.com/free-audio/clap-validator"

[dependencies]
anyhow = "1.0.58"
either = "1.9.0"
chrono = { version = "0.4.23", features = ["serde"] }
# All the claps!
clap = { version = "4.1.8", features = ["derive", "wrap_help"] }
# For CLAP 1.2.2 support
clap-sys = { git = "https://github.com/micahrj/clap-sys.git", rev = "25d7f53fdb6363ad63fbd80049cb7a42a97ac156" }
colored = "3.0.0"
crossbeam = "0.8.1"
libloading = "0.9.0"
log = "0.4"
log-panics = "2.0"
midi-consts = "0.1.0"
parking_lot = "0.12.1"
rand = "0.9.2"
rand_pcg = "0.9.0"
rayon = "1.6.1"
regex = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.12"
strum = "0.27.2"
strum_macros = "0.27.2"
tempfile = "3.3"
textwrap = { version = "0.16.2", features = ["terminal_size"] }
walkdir = "2.3"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10.1"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
